### ISSUE TITLE
上传

### ISSUE THREAD

**Issue by Yuanyixue** [jokin1999/NodeMCU-IOController#1]
刚接触esp8266，请问如何上传全部文件至NodeMCU？现阶段只会烧写现成的bin文件或刷写lua文件。。

**Comment by josark2005** [comment]
刷写lua文件即可

**Comment by Yuanyixue** [comment]
谢谢！
您能不能给我一份带注释的int.lua文件？！
我尝试修改了int.lua文件的几项后上传了全部lua与html文件，连接nodemcu输入此时nodemcu的ip后没有打开io的控制网页 >_

**Comment by josark2005** [comment]
init.lua文件中是带注释的

以下设置是直连nodemcu的wifi设置
```
apcfg = {
    ssid = "node_wifi",
    pwd = "12345678"
}
```
以下设置是使用nodemcu连接现存wifi的设置
```
wificfg = {
    ssid = "",
    pwd = "",
    auto = true
}
```
如果您使用的是后者，请确保局域网内互通

**Comment by Yuanyixue** [comment]
感谢！
已经完成了！之前失败是因为没添加http、sjson组件>_
